import { Router } from 'express';
import { listMarkets, getMarket } from '../controllers/marketController.js';
import { createMarket, updateMarket, deleteMarket } from '../controllers/adminController.js';
import { authenticateUser, requireAdmin } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
const router = Router();
router.get('/', asyncHandler(listMarkets));
router.get('/:id', asyncHandler(getMarket));
router.post('/', authenticateUser, requireAdmin, asyncHandler(createMarket));
router.put('/:id', authenticateUser, requireAdmin, asyncHandler(updateMarket));
router.delete('/:id', authenticateUser, requireAdmin, asyncHandler(deleteMarket));
export default router;
