import { Router } from 'express';
import { listConversations, createConversation, listMessages, sendMessage } from '../controllers/messageController.js';
import { authenticateUser } from '../middleware/auth.js';
import { asyncHandler } from '../utils/asyncHandler.js';
const router = Router();
router.use(authenticateUser);
router.get('/', asyncHandler(listConversations));
router.post('/', asyncHandler(createConversation));
router.get('/:id/messages', asyncHandler(listMessages));
router.post('/:id/messages', asyncHandler(sendMessage));
export default router;
