import { Router } from 'express';
import { listProducts, getProduct, searchProducts, createProduct, updateProduct, updateProductStatus, deleteProduct } from '../controllers/productController.js';
import { authenticateFirebaseUser, authenticateUser, requireSeller } from '../middleware/auth.js';
const router = Router();
router.get('/', listProducts);
router.get('/search', searchProducts);
router.get('/shop/:shopId', listProducts);
router.get('/market/:marketId', listProducts);
router.get('/category/:categoryId', listProducts);
router.get('/:id', getProduct);
router.post('/', authenticateUser, requireSeller, createProduct);
router.put('/:id', authenticateUser, requireSeller, updateProduct);
router.patch('/:id/status', authenticateUser, requireSeller, updateProductStatus);
router.delete('/:id', authenticateFirebaseUser, deleteProduct);
export default router;
