import React, { useState, useRef, useEffect } from 'react';
import { MessageSquare, Bell, Heart, ChevronDown, User as UserIcon, Menu, X, Store, ShoppingBag } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { AccountDropdown } from './AccountDropdown';
import { NavigationTab } from '../types';

export const Header: React.FC = () => {
  const { currentUser, activeNavTab, navigateTo, wishlist, conversations, setIsMessagesOpen, setIsCartOpen, cart } = useApp();
  const [isAccountOpen, setIsAccountOpen] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [isNotificationsOpen, setIsNotificationsOpen] = useState(false);
  const notifRef = useRef<HTMLDivElement>(null);
  const totalUnreadMessages = conversations.reduce((sum, c) => sum + c.unreadCount, 0);
  const totalCartCount = cart.reduce((sum, item) => sum + item.quantity, 0);

  useEffect(() => {
    const handleDocClick = (e: MouseEvent) => { if (notifRef.current && !notifRef.current.contains(e.target as Node)) setIsNotificationsOpen(false); };
    document.addEventListener('mousedown', handleDocClick);
    return () => document.removeEventListener('mousedown', handleDocClick);
  }, []);
  const handleNavClick = (tab: NavigationTab) => { navigateTo(tab === 'markets' ? 'markets' : tab === 'shops' ? 'shops' : tab === 'categories' ? 'categories' : 'about'); setIsMobileMenuOpen(false); };

  return (
    <header className="sticky top-0 z-40 bg-[#F7F5F3]/95 backdrop-blur-md border-b border-gray-200/60 transition-all">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex items-center justify-between h-20">
        <div id="brand-logo-btn" onClick={() => navigateTo('markets')} className="flex items-center gap-3 cursor-pointer select-none group"><div className="w-11 h-11 rounded-2xl bg-[#8067E8] text-white flex items-center justify-center shadow-md group-hover:scale-105 transition-transform"><span className="font-extrabold text-2xl font-sans tracking-tight">C</span></div><div><span className="text-xl sm:text-2xl font-extrabold text-[#20243A] tracking-tight group-hover:text-[#8067E8] transition-colors">claymarket</span><p className="text-[11px] text-[#737B89] font-medium -mt-1">Your local marketplace</p></div></div>
        <nav className="hidden md:flex items-center space-x-1 lg:space-x-3 bg-white/70 px-4 py-1.5 rounded-full border border-white/80 shadow-sm">{(['markets', 'shops', 'categories', 'about'] as NavigationTab[]).map(tab => { const label = tab === 'about' ? 'About Us' : tab.charAt(0).toUpperCase() + tab.slice(1); const isActive = activeNavTab === tab; return <button key={tab} id={`nav-tab-${tab}`} onClick={() => handleNavClick(tab)} className={`relative px-4 py-2 text-sm font-semibold rounded-full transition-all duration-200 ${isActive ? 'text-[#8067E8] bg-[#F1EDFD] shadow-xs' : 'text-[#505767] hover:text-[#20243A] hover:bg-gray-100/60'}`}>{label}{isActive && <span className="absolute bottom-1 left-1/2 -translate-x-1/2 w-3 h-1 bg-[#8067E8] rounded-full" />}</button>; })}</nav>
        <div className="flex items-center gap-2 sm:gap-3">
          <button id="header-messages-btn" onClick={() => setIsMessagesOpen(true)} aria-label={`Messages${totalUnreadMessages ? `, ${totalUnreadMessages} unread` : ''}`} className="relative p-2.5 rounded-full bg-white hover:bg-gray-50 text-[#20243A] border border-gray-200/70 shadow-xs hover:shadow-sm transition-all active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8]"><MessageSquare className="w-5 h-5 text-[#374151]" />{totalUnreadMessages > 0 && <span className="absolute -top-1 -right-1 min-w-5 h-5 px-1 bg-[#8067E8] text-white text-[10px] font-bold rounded-full flex items-center justify-center ring-2 ring-[#F7F5F3] shadow-xs animate-pulse">{totalUnreadMessages}</span>}</button>
          <div className="relative hidden sm:block" ref={notifRef}><button id="header-notifications-btn" onClick={() => setIsNotificationsOpen(v => !v)} aria-expanded={isNotificationsOpen} aria-haspopup="dialog" aria-label="Notifications" className="relative p-2.5 rounded-full bg-white hover:bg-gray-50 text-[#20243A] border border-gray-200/70 shadow-xs hover:shadow-sm transition-all active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8]"><Bell className="w-5 h-5 text-[#374151]" /><span className="absolute top-1.5 right-1.5 w-2.5 h-2.5 bg-[#FF6B6B] rounded-full ring-2 ring-white" /></button>{isNotificationsOpen && <div role="dialog" aria-label="Notifications" className="absolute right-0 mt-3 w-80 bg-white rounded-3xl p-4 shadow-2xl border border-gray-100 z-50 animate-in fade-in slide-in-from-top-2 duration-200"><div className="flex items-center justify-between pb-2.5 border-b border-gray-100"><h4 className="font-bold text-sm text-[#20243A]">Notifications</h4><span className="text-[11px] bg-[#DDD4FF] text-[#553BB8] font-bold px-2 py-0.5 rounded-full">2 New</span></div><div className="py-2 space-y-2"><div className="p-2.5 bg-[#FAF8FE] rounded-2xl border border-[#EDE7FD] flex gap-3 items-start hover:shadow-sm transition-shadow"><div className="w-8 h-8 rounded-xl bg-[#DDD4FF] text-[#8067E8] flex items-center justify-center shrink-0"><Store className="w-4 h-4" /></div><div><p className="text-xs font-bold text-[#20243A]">Aminul Slipper Shop</p><p className="text-[11px] text-[#737B89]">Fresh new arrival: Waterproof Monsoon Clogs available now!</p><span className="text-[10px] text-gray-400 mt-1 block">15 mins ago</span></div></div><div className="p-2.5 bg-gray-50 rounded-2xl flex gap-3 items-start hover:shadow-sm transition-shadow"><div className="w-8 h-8 rounded-xl bg-[#CBEFD9] text-[#176F43] flex items-center justify-center shrink-0"><ShoppingBag className="w-4 h-4" /></div><div><p className="text-xs font-bold text-[#20243A]">Kachumara Market Day</p><p className="text-[11px] text-[#737B89]">Weekly Haat is active today with over 60+ verified stalls.</p><span className="text-[10px] text-gray-400 mt-1 block">2 hours ago</span></div></div></div></div>}</div>
          <button id="header-wishlist-btn" onClick={() => navigateTo('wishlist')} aria-label={`Wishlist${wishlist.length ? `, ${wishlist.length} saved` : ''}`} className="hidden sm:inline-flex relative p-2.5 rounded-full bg-white hover:bg-gray-50 text-[#20243A] border border-gray-200/70 shadow-xs hover:shadow-sm transition-all active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8]"><Heart className="w-5 h-5 text-[#374151]" />{wishlist.length > 0 && <span className="absolute -top-1 -right-1 min-w-5 h-5 px-1 bg-[#FF6B8B] text-white text-[10px] font-bold rounded-full flex items-center justify-center ring-2 ring-[#F7F5F3]">{wishlist.length}</span>}</button>
          {totalCartCount > 0 && <button id="header-cart-btn" onClick={() => setIsCartOpen(true)} aria-label={`Cart, ${totalCartCount} items`} className="hidden sm:flex items-center gap-1.5 px-3 py-2 rounded-full bg-[#8067E8] text-white font-bold text-xs shadow-md hover:bg-[#6E52E2] active:scale-95 transition-all focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8]"> <ShoppingBag className="w-4 h-4" /><span className="transition-transform">{totalCartCount}</span></button>}
          <div className="relative"><button id="account-dropdown-trigger" onClick={() => setIsAccountOpen(!isAccountOpen)} aria-expanded={isAccountOpen} className="flex items-center gap-2 pl-2 pr-3 py-1.5 bg-white hover:bg-gray-50 rounded-full border border-gray-200/80 shadow-xs transition-all cursor-pointer focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8]">{currentUser.role === 'guest' ? <div className="w-7 h-7 rounded-full bg-gray-100 text-gray-600 flex items-center justify-center"><UserIcon className="w-4 h-4" /></div> : <img loading="lazy" decoding="async" src={currentUser.avatar} alt={currentUser.name} className="w-7 h-7 rounded-full object-cover ring-1 ring-[#DDD4FF]" />}<span className="hidden sm:inline text-sm font-semibold text-[#20243A] max-w-[90px] truncate">{currentUser.role === 'guest' ? 'Guest' : currentUser.name.split(' ')[0]}</span><ChevronDown className={`w-4 h-4 text-gray-500 transition-transform ${isAccountOpen ? 'rotate-180' : ''}`} /></button><AccountDropdown isOpen={isAccountOpen} onClose={() => setIsAccountOpen(false)} /></div>
          <button id="mobile-menu-toggle-btn" onClick={() => setIsMobileMenuOpen(!isMobileMenuOpen)} aria-expanded={isMobileMenuOpen} aria-label={isMobileMenuOpen ? 'Close menu' : 'Open menu'} className="md:hidden p-2.5 rounded-full bg-white border border-gray-200 text-[#20243A] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8]">{isMobileMenuOpen ? <X className="w-5 h-5" /> : <Menu className="w-5 h-5" />}</button>
        </div>
      </div></div>
      {isMobileMenuOpen && <div className="md:hidden bg-white border-b border-gray-200 px-6 py-4 space-y-3 animate-in slide-in-from-top-4 duration-200"><div className="space-y-1">{(['markets', 'shops', 'categories', 'about'] as NavigationTab[]).map(tab => <button key={tab} onClick={() => handleNavClick(tab)} className={`w-full text-left px-4 py-2.5 rounded-xl font-semibold text-sm transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8] ${activeNavTab === tab ? 'bg-[#F1EDFD] text-[#8067E8]' : 'text-[#20243A] hover:bg-gray-50'}`}>{tab === 'about' ? 'About Us' : tab.charAt(0).toUpperCase() + tab.slice(1)}</button>)}</div><div className="pt-3 border-t border-gray-100 flex items-center justify-between"><span className="text-xs text-[#737B89] font-medium">Role: <strong className="text-[#8067E8]">{currentUser.role}</strong></span><button onClick={() => { setIsAccountOpen(true); setIsMobileMenuOpen(false); }} className="text-xs text-[#8067E8] font-bold underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#8067E8] rounded">Account Options</button></div></div>}
    </header>
  );
};