import { doc, deleteField, updateDoc } from 'firebase/firestore';
import { firebaseDb } from '../firebase';

const API_BASE_URL = (import.meta.env.VITE_API_URL || '/api').replace(/\/$/, '');
const BUTTON_ID = 'claymarket-delete-shop-button';
const MODAL_ID = 'claymarket-delete-shop-modal';
const getAuthToken = () => localStorage.getItem('claymarket_auth_token') || '';
const getFirebaseUserIdFromToken = (token:string) => { try { const payload=token.split('.')[1]; if(!payload)return ''; const decoded=JSON.parse(atob(payload.replace(/-/g,'+').replace(/_/g,'/'))); return String(decoded.user_id||decoded.sub||''); } catch { return ''; } };
const request = async (path:string, options:RequestInit={}) => { const headers=new Headers(options.headers||{}); const token=getAuthToken(); if(token)headers.set('Authorization',`Bearer ${token}`); const response=await fetch(`${API_BASE_URL}${path}`,{...options,headers}); const payload=await response.json().catch(()=>({})); if(!response.ok||payload?.success===false)throw new Error(payload?.message||`Request failed (${response.status})`); return payload?.data??payload; };
const getOwnedShop = async () => { const uid=getFirebaseUserIdFromToken(getAuthToken()); if(!uid)return null; const shops=await request('/shops?limit=100'); const list=Array.isArray(shops)?shops:[]; return list.find((shop:any)=>String(shop?.ownerId?._id||shop?.ownerId||'')===uid)||null; };
const removeExistingModal=()=>document.getElementById(MODAL_ID)?.remove();
const clearDeletedShopAssociation=async(uid:string)=>{ if(!firebaseDb||!uid)return; // IMPORTANT: keep the Firebase user ID/account; remove shop/seller association only.
 await updateDoc(doc(firebaseDb,'users',uid),{shopId:deleteField(),sellerId:deleteField(),sellerLocation:deleteField()}); };
const showDeleteModal=(shop:any)=>{ removeExistingModal(); let step=1; const overlay=document.createElement('div'); overlay.id=MODAL_ID; overlay.style.cssText='position:fixed;inset:0;z-index:99999;display:flex;align-items:center;justify-content:center;padding:20px;background:rgba(15,18,30,.58);backdrop-filter:blur(4px);font-family:inherit;'; const render=()=>{ overlay.innerHTML=`<div style="width:min(460px,100%);background:#fff;border-radius:24px;padding:28px;box-shadow:0 24px 70px rgba(0,0,0,.25)"><h2 style="margin:0 0 8px;color:#20243A">Delete your shop?</h2><p style="color:#4b5563;line-height:1.5">${step===1?'This permanently deletes your shop and its products. Your seller account will remain active.':'Final confirmation: this action cannot be undone.'}</p><div style="display:flex;gap:10px;justify-content:flex-end"><button data-cancel>Cancel</button>${step===1?'<button data-next style="background:#dc2626;color:white">Continue</button>':'<button data-back>Back</button><button data-confirm style="background:#b91c1c;color:white">Yes, Delete Shop</button>'}</div><p data-error style="display:none;color:#dc2626"></p></div>`; overlay.querySelector('[data-cancel]')?.addEventListener('click',removeExistingModal); overlay.querySelector('[data-next]')?.addEventListener('click',()=>{step=2;render()}); overlay.querySelector('[data-back]')?.addEventListener('click',()=>{step=1;render()}); overlay.querySelector('[data-confirm]')?.addEventListener('click',async(event)=>{const button=event.currentTarget as HTMLButtonElement; button.disabled=true; button.textContent='Deleting...'; try { const uid=getFirebaseUserIdFromToken(getAuthToken()); await request(`/shops/${encodeURIComponent(String(shop._id||shop.id))}`,{method:'DELETE'}); await clearDeletedShopAssociation(uid); localStorage.removeItem('claymarket_shops_v2'); localStorage.removeItem('claymarket_products_v2'); removeExistingModal(); window.location.assign('/shops'); } catch(error:any) { const errorEl=overlay.querySelector('[data-error]') as HTMLElement|null; if(errorEl){errorEl.textContent=error?.message||'Could not delete the shop.';errorEl.style.display='block';} button.disabled=false;button.textContent='Yes, Delete Shop'; }}); }; document.body.appendChild(overlay);render(); };
const install=async()=>{ if(document.getElementById(BUTTON_ID))return; if(!Array.from(document.querySelectorAll('h1')).some(el=>el.textContent?.includes('Seller Dashboard')))return; try { const shop=await getOwnedShop(); if(!shop)return; const button=document.createElement('button'); button.id=BUTTON_ID;button.type='button';button.textContent='Delete Shop';button.style.cssText='padding:10px 16px;border-radius:999px;border:1px solid #fecaca;background:#fff7f7;color:#b91c1c;font-weight:800;font-size:12px;cursor:pointer;transition:.15s;';button.addEventListener('mouseenter',()=>{button.style.background='#fee2e2'});button.addEventListener('mouseleave',()=>{button.style.background='#fff7f7'});button.addEventListener('click',()=>showDeleteModal(shop)); const header=Array.from(document.querySelectorAll('h1')).find(el=>el.textContent?.includes('Seller Dashboard'))?.closest('div[class*="rounded-3xl"]'); const actions=header?.querySelector('div.flex.items-center.gap-3')||header?.lastElementChild; if(actions)actions.appendChild(button); } catch(error){console.error('[Claymarket] Failed to initialize shop deletion',error);} };
let timer:number|undefined; const observe=()=>{window.clearTimeout(timer);timer=window.setTimeout(install,250)}; if(typeof window!=='undefined'){const observer=new MutationObserver(observe);observer.observe(document.body,{childList:true,subtree:true});window.addEventListener('popstate',observe);observe();}
